services:
  connector-wazuh:
    image: ghcr.io/misje/opencti-wazuh-connector:0.3.0
    restart: always
    environment:
      # A timezone is needed for datetime tools to work as expected:
      - TZ=UTC
      - USE_TZ=true
      - OPENCTI_URL=https://mycti.example.org
      - OPENCTI_TOKEN=84387577-27ac-4751-b268-6893045aa73c
      - CONNECTOR_ID=81f9d582-2b4e-45f1-98b6-f33492d66b6e
      - CONNECTOR_NAME=Wazuh
      - CONNECTOR_SCOPE=Artifact,Directory,Domain-Name,Email-Addr,Hostname,IPv4-Addr,IPv6-Addr,Mac-Addr,Network-Traffic,Process,Software,StixFile,Url,User-Account,User-Agent,Windows-Registry-Key,Windows-Registry-Value-Type,Vulnerability,Indicator # You may also just use "all" if you want to search all available entities
      - CONNECTOR_AUTO=true
      - CONNECTOR_LOG_LEVEL=warning
      - CONNECTOR_EXPOSE_METRICS=true
      - AGENTS_AS_SYSTEMS=true
      - WAZUH_APP_URL=https://mywazuh.example.org
      - WAZUH_AUTHOR_NAME=Wazuh
      - WAZUH_BUNDLE_ABORT_LIMIT=500
      - WAZUH_CREATE_AGENT_HOSTNAME_OBSERVABLE=true
      - WAZUH_CREATE_AGENT_IP_OBSERVABLE=true
      - WAZUH_CREATE_INCIDENT=per-sighting # per-query, per-sighting, per-alert-rule, per-alert, never
      - WAZUH_CREATE_INCIDENT_RESPONSE=true
      - WAZUH_CREATE_INCIDENT_SUMMARY=true
      - WAZUH_CREATE_INCIDENT_SUMMARY=true
      - WAZUH_VULNERABILITY_INCIDENT_CVSS3_SCORE_THRESHOLD= # CVSS3 score (0–10, or empty)
      - WAZUH_VULNERABILITY_INCIDENT_ACTIVE_ONLY=true
      - WAZUH_CREATE_INCIDENT_THRESHOLD=1
      - WAZUH_RULE_EXCLUDE_LIST=
      - WAZUH_INCIDENT_RULE_EXCLUDE_LIST=
      - WAZUH_CREATE_OBS_SIGHTINGS=true
      - WAZUH_CREATE_SIGHTING_SUMMARY=true
      - WAZUH_ENRICH_FILENAME_BEHAVIOUR=create-dir,remove-path
      - WAZUH_ENRICH_URLS_WITHOUT_HOST=false
      - WAZUH_ENRICH_TYPES=all
      - WAZUH_ENRICH_LABELS=wazuh_ignore
      - WAZUH_HITS_ABORT_LIMIT=1000
      - WAZUH_IGNORE_OWN_ENTITIES=false
      - WAZUH_IGNORE_REVOKED_INDICATORS=true
      - WAZUH_INDICATOR_SCORE_THRESHOLD=
      - WAZUH_LABEL_IGNORE_LIST=hygiene,wazuh_ignore
      - WAZUH_MAX_EXTREFS=10
      - WAZUH_MAX_EXTREFS_PER_ALERT_RULE=2
      - WAZUH_MAX_NOTES=10
      - WAZUH_MAX_NOTES_PER_ALERT_RULE=2
      - WAZUH_MAX_TLP=TLP:RED
      - WAZUH_OPENSEARCH_EXCLUDE_MATCH=data.integration:opencti
      - WAZUH_OPENSEARCH_FILTER=
      - "WAZUH_OPENSEARCH_TIMEOUT=20 seconds"
      - WAZUH_OPENSEARCH_INCLUDE_MATCH=
      - WAZUH_OPENSEARCH_INDEX=wazuh-alerts-*
      - WAZUH_OPENSEARCH_LIMIT=50
      - WAZUH_OPENSEARCH_ORDER_BY=timestamp:desc
      - "WAZUH_OPENSEARCH_PASSWORD=SecretPassword" # Remember double-$ if password contains $:
      - "WAZUH_OPENSEARCH_SEARCH_AFTER=7 months ago" # No limit can cause search errors, especially with regexp queries (possibly mitigated by increasing indices.query.bool.max_clause_count)
      - WAZUH_OPENSEARCH_URL=https://mywazuh.example.org:9200
      - WAZUH_OPENSEARCH_USERNAME=cti_connector
      - WAZUH_OPENSEARCH_VERIFY_TLS=false # Set this to true if you are using a proper certificate in OpenSearch
      - WAZUH_REQUIRE_INDICATOR_DETECTION=false
      - WAZUH_REQUIRE_INDICATOR_FOR_INCIDENTS=true
      - WAZUH_SEARCH_DIRSEARCH_OPTIONS=allow-regexp,case-insensitive,ignore-trailing-slash,match-subdirs,search-filenames
      - WAZUH_SEARCH_FILESEARCH_OPTIONS=allow-regexp,case-insensitive,include-parent-dir-ref,include-reg-values,search-additional-filenames,search-filename-only,search-size
      - WAZUH_SEARCH_IGNORE_PRIVATE_ADDRS=true
      - WAZUH_SEARCH_LOOKUP_AGENT_IP=false
      - WAZUH_SEARCH_LOOKUP_AGENT_NAME=false
      - WAZUH_SEARCH_LOOKUP_HOSTNAMES_IN_CMD_LINE=false
      - WAZUH_SEARCH_LOOKUP_MAC_VARIANTS=true
      - WAZUH_SEARCH_LOOKUP_URL_INGORE_TRAILING_SLASH=false
      - WAZUH_SEARCH_LOOKUP_URL_WITHOUT_HOST=false
      - WAZUH_SEARCH_PROCSEARCH_OPTIONS=case-insensitive
      - WAZUH_SYSTEM_NAME="Wazuh SIEM"
      - WAZUH_TLPS=TLP:AMBER+STRICT
    # Set a limit on logs:
    logging:
      options:
        max-size: 50m
