# Deploy HTML docs to github-pages when "Build docs" has completed on the
# master branch

name: Deploy docs
on:
  workflow_run:
    workflows:
      - "Build docs"
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
