name: Run tests
on:
  push:
    paths:
      - .github/workflows/tests.yml
      - tests/**
      - src/**/*.py
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
      - name: Install connector dependencies
        run: pip install -r src/requirements.txt
      - name: Install test dependencies
        run: pip install -r tests/requirements.txt
      - name: Run doctests
        working-directory: tests
        run: python3 run_doctests.py
      - name: Run unit tests
        working-directory: tests/unit
        run: pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
