name: Run tests
on:
  push:
    paths:
      - .github/workflows/tests.yml
      - tests/**
      - src/**/*.py
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - tests/**
      - src/**/*.py
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
          cache: pip
      - name: Install connector dependencies
        run: pip install -r src/requirements.txt
      - name: Install test dependencies
        run: pip install -r tests/requirements.txt
      - name: Run unit tests and doctests
        env:
          PYTHONPATH: src
        # TODO: Coverage reports:
        run: pytest --doctest-glob '*.py' --doctest-glob '*.rst' --doctest-modules
